development: &development
  adapter: postgresql
  encoding: unicode
  database: nabely_development
  pool: 5
  host: localhost
  username: nabely
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: nabely_test
  pool: 5
  host: localhost
  username: nabely
  password:
